modLoader="javafml"
loaderVersion="${target_loader}"
issueTrackerURL="https://github.com/IMB11/MRU/issues"
displayURL="http://IMB11.dev/"
logoFile="assets/mru/icon.png"
authors="IMB11"
license="All-Rights-Reserved"

[[mods]]
modId="mru"
version="${mod_version}"
displayName="Mineblock's Repeated Utilities"
description="Library mod providing compatability utilities and other stuff."

[[dependencies.mru]]
modId="${loader}"
${mandatory_inclusion_field}
versionRange="${target_loader}"
ordering="NONE"
side="BOTH"

[[dependencies.mru]]
modId="minecraft"
${mandatory_inclusion_field}
versionRange="${target_minecraft}"
ordering="NONE"
side="BOTH"

[[mixins]]
config="mru.mixins.json"