modLoader="javafml"
loaderVersion = "[1,)"
issueTrackerURL="https://github.com/IMB11/IMB11/issues"
displayURL="http://IMB11.dev/"
logoFile="assets/${mod_id}/icon.png"
authors="IMB11 (mineblock11)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description="${mod_description}"

[["dependencies.${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${target_minecraft}"
ordering="NONE"
side="BOTH"