modLoader="javafml"
loaderVersion = "[1,)"
issueTrackerURL="https://github.com/IMB11/IMB11/issues"
displayURL="http://IMB11.dev/"
logoFile="assets/mru/icon.png"
authors="IMB11 (mineblock11)"
license="${mod_license}"

[[mods]]
modId="mru"
version="${mod_version}"
displayName="${mod_name}"
description="${mod_description}"

[[dependencies.mru]]
modId="${loader}"
versionRange="[2,)"
type="required"
ordering="NONE"
side="BOTH"

[[dependencies.mru]]
modId="minecraft"
type="required"
versionRange="${target_minecraft}"
ordering="NONE"
side="BOTH"

