mod.mc_dep_fabric=>=26.1
deps.minecraft=26.1.2
deps.curseforge_minecraft_version=26.1.2
publish.additionalVersions=26.1,26.1.1

deps.fabric_api=0.155.2+26.1.2

deps.backpacked=7573691
deps.badpackets=0.9.0
deps.cca=8.0.0
deps.cloth=26.1.154
deps.cold_sweat=MZG2qoxy
deps.curios=15.0.0+26.1.2
deps.fabric_seasons=2.4.2-BETA+1.21
deps.fast_item_frames=nTFFi5Ha
deps.forge_config_api_port=26.1.5
deps.framework=7810592
deps.fzzy_config=0.7.6+26.1
deps.glitchcore=2.5.0.1
deps.glowcase=2.3.0+1.21
deps.jade=26.1.0+fabric
deps.map_atlases=6345967
deps.neoforge=26.1.2.76
deps.modmenu=18.0.0-beta.1
deps.moonlight=1.21-2.18.5
deps.owo_version=0.12.21+1.21.6
deps.placeholder_api=2.7.1+1.21.6
deps.player_locator_plus=2.1.3-mc1.21.5
deps.polymer=0.13.3+1.21.6
deps.puzzles_lib=sPQhTMzj
deps.serene_seasons=26.1.2.0.2
deps.simple_seasons=1.1.0+mc1.21-1.21.1
deps.sophisticated_backpacks=26.1.2-3.25.55.1739
deps.sophisticated_core=26.1.2-1.4.45.1849
deps.surveyor=1.2.4+26.1
deps.thermoo=10.0.0-beta.4
deps.tiered_backpacks=1.0.14+26.1-fabric
deps.tough_as_nails=10.5.0.5
deps.travelers_backpack=26.1.2-11.2.6
deps.trinkets=4.0.0-beta.3+26.1
deps.useful_spyglass=0.7.0
deps.wthit_version=16.0.1
deps.xaeros_minimap=fabric-26.1.2-25.3.12
deps.xaeros_world_map=fabric-26.1.2-1.40.16
deps.yacl=3.9.3+26.1-fabric